### PR TITLE
IE9 blob fix

### PR DESCRIPTION
**Pull request by doktordirk**
https://github.com/aurelia/fetch-client/issues/59

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk One small thing to mention, is that IE9 users now have to add the correct header themselves as mentioned here: https://github.com/aurelia/fetch-client/issues/59#issuecomment-218941818

**Comment by doktordirk** [comment]
@RWOverdijk 
that should be handled here https://github.com/aurelia/fetch-client/pull/61/commits/e1cb71a6383a64e574a5eecace0f1d91445515b7#diff-ab4b11a4a0f024bbfafeda47a386d545R173

**Comment by RWOverdijk** [comment]
@doktordirk But when you set the bode (JSON.stringify(body);) there's no type defined. Or am I missing something?

**Comment by doktordirk** [comment]
@RWOverdijk hmm right. got confused, since we don't use that part of utils json anyways

**Comment by doktordirk** [comment]
oh well

**Comment by bryanrsmith** [comment]
Yeah, the only reason to use this utility is to ensure the content type is set appropriately. I think you just need to include a blob polyfill in IE9.

**Comment by bryanrsmith** [comment]
Actually, the [fetch polyfill](https://github.com/github/fetch) only claims IE10+ support :-/

**Pull request closed without merging**
