### PR TITLE
Fixes for passing Request to fetch

### PR DESCRIPTION
**Pull request by timbell**
Don't create a new request when one is passed to fetch but do apply any default headers

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you review this?

**Comment by EisenbergEffect** [comment]
@bryanrsmith ping...

**Comment by bryanrsmith** [comment]
Sorry for the delay.

@timbell I like the change, but it breaks functionality if we don't apply the base URL. We can't do that without copying the Request, which was why that was added. I don't think we can accept the breaking change at this point. Maybe when we reach 2.0?

Was the Request copying causing a problem for you? If so, is there another way to solve it?

**Comment by timbell** [comment]
Yes, there are the problems with the Request copying - see my comment on issue [#1](https://github.com/aurelia/fetch-client/issues/1#issuecomment-186124700) which led to this pull request.

**Comment by bryanrsmith** [comment]
Right, makes sense. So this case has never worked right, which means we can
make the change without further breaking anyone.

Would you mind just rebasing to clean up those extra commits? Thanks, and
sorry again for neglecting the PR.

**Comment by timbell** [comment]
Sorry, I've got in a total pickle with git - it's not something I use day to day. What's the easiest way to start again?

**Comment by Gheoan** [comment]
@timbelk 

Remove the commits, while preserving your work:

```shell
git reset --soft master
```
Commit and push:
```shell
git commit
```
```shell
git push
```

**Comment by timbell** [comment]
@Gheoan - thanks. Is the pull request usable now? (I notice that the Travis build has failed but it did before too.)

**Comment by timbell** [comment]
Could I ask the status of this? Do I need to fix stuff in git? If so, I will need instructions I'm afraid.

**Comment by EisenbergEffect** [comment]
Right now the status says that the branch has conflicts. You would need to rebase on master. If you can do that, we'll get @bryanrsmith to make one final review. Assuming all tests pass and we have a CLA signature, I can get it in immediately and make a release.

**Comment by timbell** [comment]
I've done:

`git fetch origin`
`git rebase origin/master`

Is that right? What do I do next?

**Comment by AshleyGrant** [comment]
@timbell please follow the instruction in my youtube video here: https://www.youtube.com/watch?v=M7ZYkjOWr6g

**Comment by EisenbergEffect** [comment]
Ok, looks like there are no conflicts. I see that the travis-ci is failing. @timbell Can you run the unit tests and also run the linting to make sure everything is passing on your local machine. If not, we need to see if there's something funny going on with travis. Please ping me and let me know.

**Comment by timbell** [comment]
Unit tests pass:
`07 04 2016 15:48:10.601:WARN [karma]: No captured browser, open http://localhost:9876/`
`07 04 2016 15:48:10.616:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/`
`07 04 2016 15:48:10.637:INFO [launcher]: Starting browser Chrome`
`07 04 2016 15:48:12.050:INFO [Chrome 49.0.2623 (Windows 8.1 0.0.0)]: Connected on socket /#tE9trb1JavToo3h1AAAA with id
64963748`
`Chrome 49.0.2623 (Windows 8.1 0.0.0): Executed 32 of 32 SUCCESS (0.047 secs / 0.023 secs)`

How do I run the linting?

**Comment by EisenbergEffect** [comment]
`gulp lint`

**Comment by timbell** [comment]
`[17:06:00] Using gulpfile ...\fetch-client\gulpfile.js`
`[17:06:00] Starting 'lint'...`
`[17:06:02] Finished 'lint' after 1.76 s`

So I guess ok?

**Comment by EisenbergEffect** [comment]
Yes. So, something else is going on here. I wonder if the tests aren't configured quite right for the CI environment. I'll look into it. Thanks! We'll get this merged shortly.

**Comment by bryanrsmith** [comment]
I think the failures are left over from the core-js removal. We probably just need to add the polyfill library to the karma config. I might have time to take a look in a few hours.

**Pull request merged**
