### PR TITLE
Hotfix/keep baseurl

### PR DESCRIPTION
**Pull request by RWOverdijk**
Upon running configure a second time, the baseUrl got overridden. This is very annoying when combining multiple plugins that use the fetch-client. The same should be done for the defaults, but that's a bit more complex.

### CODE REVIEW

**Comment by bryanrsmith** [comment]
Thanks, @RWOverdijk. I agree this is a problem with the current design. It's not intended to be used as a singleton between modules that need different configurations, but since Aurelia's DI library defaults to a singleton lifetime that's how it ends up being used most of the time.

I think it might be better if we try to discourage reconfiguration, since that could lead to situations where a second module changes the configuration while a first module still needs the original configuration. What if we change the default registration to transient, so that you get a new instance each time? That should avoid the 'shared mutable state by default' problem we have now, while still allowing that behavior via DI configuration if desired. What do you think?

A couple alternatives:
1. We could make `HttpClient` immutable so that `.configure()` returns a new instance instead of mutating the existing instance.
2. We could make `HttpClient` immutable but use a factory to create instances instead of letting DI do it. That might make the immutability clearer to the calling code. You'd inject the factory and then use something like `this.httpClient = httpClientFactory.create(config => config.withBaseUrl(...))`.

As a side note, the approach I personally use is to explicitly register factories with the DI container for services that need HttpClients. This makes it easier to change configurations from environment settings, simplifies testing because the HttpClient mock can be simpler, and it avoids issues such as what you're running into with singletons. Eg, in my main.js:

```js
container.registerSingleton(UserService, () =>
    new UserService(
        new HttpClient().configure(c => c.withBaseUrl('/users/'))
    )
);
```

/cc @EisenbergEffect

**Comment by RWOverdijk** [comment]
@bryanrsmith I disagree with you. I don't want to reconfigure my endpoint for every module I use (it's three so far, so not a HUGE problem, but still.). One option I can think of, is that a module should be allowed to fork off of the original with custom configurations, so that the defaults persist (such as baseUrl). That way a module can set credentials to true, while still having the defaults of the main instance.

The problem with this, is that you can't (easily) sync configuration if you spawn a new instance.

The reason I made this PR is for aurelia-auth. It configures the interceptor that sets the bearer token, which causes the baseUrl to drop. I could just configure it again, but I don't feel like it's the place.

**Comment by bryanrsmith** [comment]
Could you link the code, or post an example of what you're trying to do? I'd prefer that the configure method left the client in a consistent state, rather than merging configs.

**Comment by RWOverdijk** [comment]
@bryanrsmith It's really simple. I configure a baseUrl, and aurelia-auth [configures interceptors](https://github.com/SpoonX/aurelia-auth/blob/master/src/app.fetch-httpClient.config.js#L21,L39) which resets the baseUrl.

It's a singleton and shouldn't do that. I want to _add_. Not overwrite.

**Comment by bryanrsmith** [comment]
I see. The problem is that it is **not** a singleton. It **may** be a singleton. This code will not work if the application doesn't use Aurelia's default conventions or changes the registration of `HttpClient`. I would suggest either requiring the `HttpClient` instance to be passed in, or directly exporting the interceptor to allow the consumer to control its use.

**Comment by RWOverdijk** [comment]
And that's fine. But right now, this is how it works. Whatever instance I get (which I **chose** to keep a singleton, which is the most logical for most apps anyway) I want to configure. I want it to maintain its baseUrl. Sure, I could pass in the HttpClient I wish to use, but I'd still want to configure it, and it would still reset the baseUrl.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Was there a conclusion on this?

**Comment by bryanrsmith** [comment]
I think we'll be moving toward making the client transient by default and possibly also preventing reconfiguration, since it usually results in unexpected behavior.

@RWOverdijk I'm sorry this isn't what you were hoping for. In your case it looks like you only need to add an interceptor. You can do this without using the `.configure()` method by pushing the interceptor onto the `httpClient.interceptors` array. That should avoid conflicts with configuration values set outside your code.

**Comment by RWOverdijk** [comment]
I wholeheartedly disagree with you. But it's not my repo. :)

**Comment by bryanrsmith** [comment]
@RWOverdijk I'm happy to discuss further if you have a better alternative. I just didn't see any suggestions. The problematic scenario that we need to accommodate is:

1. `class GitHubService` requests an `HttpClient` and configures it with a `baseUrl` of `'https://api.github.com/'`.
2. `class UserService` requests an `HttpClient` and configures it with a `baseUrl` of `'/users'`.

Problem: The two services received the same singleton instance, and the second one blew away the configuration set by the first. The next time data is fetched the request will fail in an unexpected way.

**Comment by RWOverdijk** [comment]
@bryanrsmith In my opinion, in that case it's up to the developer to get a new instance in stead. I believe that separate endpoints are the exception, not the rule. It's either that, or like you suggetsed go completely transient and pass along your instances to your heart's desire. :)

**Pull request closed without merging**
