### PR TITLE
chore(doc): update whatwg-fetch.d.ts to latest version

### PR DESCRIPTION
**Pull request by RomkeVdMeulen**
https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/whatwg-fetch/whatwg-fetch.d.ts

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bryanrsmith Is this safe to merge? I see that CI is broken. Are we having issues with that?

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you review?

**Comment by bryanrsmith** [comment]
Looks reasonable. @cmichaelgraham might be better to review since it looks like he made some changes to the previous version.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Can you review this?

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Can you review this please?

**Comment by EisenbergEffect** [comment]
Closing this in favor or an alternate solution. @niieani can you submit the PR for that?

**Comment by niieani** [comment]
@EisenbergEffect let's do that once the new typings generation is in place.

**Comment by EisenbergEffect** [comment]
Sounds like a plan.

**Pull request closed without merging**
