### PR TITLE
Add type annotations

### PR DESCRIPTION
**Pull request by bryanrsmith**
Not ready yet due to a couple outstanding issues with the dts generator.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bryanrsmith Where is this PR at? Looks like things may have evolved since it was made. Can it be closed?

**Comment by bryanrsmith** [comment]
It's waiting on feedback from @cmichaelgraham for some outstanding issues with the dts generator. I'll update it tonight so it merges cleanly. Once I do that I think we could go ahead and merge it, since the type annotations are correct, and the problem is just with the generator (I think). Will follow up once I get it updated.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Can you comment on the related issues and if they have been addressed?

**Comment by cmichaelgraham** [comment]
i haven't done it yet - i will try to look at it tonight when i get home (in a few hours) :+1:

**Comment by bryanrsmith** [comment]
Rebased & ready to go, if @cmichaelgraham approves :-)

**Pull request merged**
